---
title: Barbara Billoud
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: bbceramic@gmail.com
description: 'Un jardin de céramique. Modifier cette ligne dans _config.yml. Elle
  apparaîtra  dans le head meta des résultats (pour les résultats de recherche Google)
  et dans la description du site feed.xml.

'
baseurl: 
url: 
twitter_username: barbarabilloud
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
